### ISSUE TITLE
Missing resource header.svg; where are we storing graphics assets?

### ISSUE THREAD

**Issue by GiselleSerate** [aryam7/studycloud#18]
In a subfolder of assets?

**Comment by aryam7** [comment]
I believe we can put them wherever we want because of [Laravel Mix's URL Processing](https://laravel.com/docs/5.5/mix#url-processing). This is probably the best method.

**Comment by aryam7** [comment]
If we choose to do otherwise, we're gonna have to make sure the images are somehow publicly accessible, which means they will have to be in the public folder, not in assets. The framework says something about [creating a symlink from public/storage to storage/app/public](https://laravel.com/docs/5.5/filesystem#the-public-disk).
I don't think this will apply to us, though, because we don't plan on using "zero downtime deployment systems."

**Comment by GiselleSerate** [comment]
For future reference: if your image links are not working, use: 
`<object type="image/svg+xml" data="{{ URL::asset('storage/images/imagename.svg') }}"> </object>`
Use storage/images even though it's actually in storage/app/public/images/imagename.svg because of the symlink.
