### ISSUE TITLE
Topic and Resource Refactor

### ISSUE THREAD

**Issue by aryam7** [aryam7/studycloud#32]
1. Move the topic descendants/ascendants and other functions out of the Topic Model and into the Topic Controller
2. Recreate the descendants function for topics? This function needs to return a flat list of the recursive parent of a topic.
3. Read over Andrew's code, although it's probably perfect. (of course it is -Andrew)
4. Consider merging the Topic and Tree Controllers? Or creating a Topic Repository? Is this what a Topic Repository is for? Maybe?

**Comment by aryam7** [comment]
![20180216_221003](https://user-images.githubusercontent.com/23412689/36625861-8a0c1052-18dc-11e8-8120-c68cd06e2f8e.jpg)

**Comment by aryam7** [comment]
#### To do next:
- evaluate the functions in the Resource model and figure out if they need their own repository, as well
- consider moving the getTopLevelTopics() function out of the Topic model
- modify the add() function on the TopicTreeController
- alter the TopicTreeController to call the TopicRepository

**Comment by aryam7** [comment]
New idea regarding nodes and connections data members in TopicTreeController:
Do we really need them? Couldn't we just have one collection data member instead?

**Comment by aryam7** [comment]
#### Stuff to do for the ResourceRepository:
- [x] move the necessary functions out of the Resource model into the ResourceRepository
- [ ] rewrite all parameters and code for the functions that you moved so that they take a resource with which to work
- [ ] create a function that returns the resources for each topic in a given list of topic_ids and have the TopicTreeController call it. ideally, the data should be returned as nodes and connections. also make sure that it is returning data as collections (not models)

**Comment by aryam7** [comment]
#### Comments on @asd848's code (which has now been moved to the ResourceRepository)
The removeFamily() function should take a collection of disallowedTopics so that it doesn't have to re-calculate ancestors and descendants.

**Comment by aryam7** [comment]
#### New thoughts on the ResourceRepository and TopicRepository
Is it really appropriate to have functions from these repositories return data in the nodes/connections format? Isn't that format specific to the TopicTreeController? Are we really going to use this format anywhere else?
If we think that the format will be used elsewhere, would it better to use a class that converts collections of models into the nodes/connections format so that we can be more flexible?

**Comment by asd848** [comment]
Progress on moveResource:

- We want to check if the topic we're moving the resource into has any relative topics that also contain the resource. If it does, we want to remove the relative topics.

In order to do that, we're creating a removeFamily function, which will make use of the disallowedTopics function. The disallowedTopics function should contain all the topics that are related to the resource, including ancestors and descendants of the topics. The topics should also have a pivot, formatted like this: [parent_id,=x topic_id=y]. 

We want removeFamily to recurse through each of the topics that currently belong to the resource, **except** for the topic that we're moving the resource into. We are going to traverse a tree in both directions making use of the pivots, moving until we reach the end of the tree, or until we hit the topic we want to move the resource into (newTopic). If we hit the topic, we  remove the input to the recursion function that got us there. If we don't, we leave it. 

**NOTE: Topics on the same level can have the same resource.**

**Comment by aryam7** [comment]
![20180331_203626](https://user-images.githubusercontent.com/23412689/38775165-6dd12a28-4030-11e8-8eac-f56bef5b626a.jpg)

**Comment by aryam7** [comment]
#### to do next:
continue trying to fix isAncestor and isDescendant
apparently, disallowedTopics does not have pivot attributes as collections. fix that
keep debugging with `$disallowed = App\Repositories\ResourceRepository::disallowedTopics(App\Resource::find(6)); (new App\Repositories\ResourceRepository)->isDescendant(6, 9, $disallowed)`
after finished debugging, get rid of three print statements in the code. also change isAncestor and isDescendant back to private functions

**Comment by aryam7** [comment]
For testing purposes, use resource 6. It has these relationships:
![20180421_103654-1](https://user-images.githubusercontent.com/23412689/39087087-397a6c9c-4550-11e8-9ed4-785fa1af5106.jpg)
